spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5440/auth_db
    username: auth_user
    password: auth_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

server:
  port: 8081