spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5441/customer_db
    username: customer_user
    password: customer_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: customer-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.mayis.customer_service.event"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.mayis.customer_service.event.UserRegisteredEvent

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: INFO

app:
  kafka:
    topics:
      user-registered: user.registered
      customer-created: customer.created

server:
  port: 8082
