spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/**,/api/v1/user/**,/api/v1/roles/**
            - id: customer-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/customers/**
            - id: account-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/accounts/**
            - id: audit-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/audit-logs/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO

jwt:
  secret: 8f3d9f4c7e8a1b2c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8
  issuer: auth-service
  audience: banking-core-platform

server:
  port: 8080
