spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5442/account_db
    username: account_user
    password: account_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.mayis.account_service.event"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: INFO

app:
  kafka:
    topics:
      customer-created: customer.created
      account-created: account.created

server:
  port: 8083
